# Generated by Django 2.2 on 2019-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresinstrument',
            name='depth',
            field=models.IntegerField(default=1, verbose_name='주거래월물'),
        ),
        migrations.AlterField(
            model_name='futuresinstrument',
            name='exchange',
            field=models.CharField(choices=[('CME', 'CME'), ('NYMEX', 'NYMEX'), ('CBOT', 'CBOT'), ('EUREX', 'EUREX'), ('HKEX', 'HKEX'), ('SGX', 'SGX'), ('ICE_US', 'ICE_US'), ('LIFFE', 'LIFFE'), ('SHFE', 'SHFE'), ('MGEX', 'MGEX'), ('MX', 'MX'), ('CBOE', 'CBOE')], max_length=16, verbose_name='거래소'),
        ),
        migrations.AlterField(
            model_name='futuresinstrument',
            name='tickprice',
            field=models.DecimalField(decimal_places=4, max_digits=7, verbose_name='호가당 가격'),
        ),
    ]
