# Generated by Django 2.2 on 2019-12-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20191222_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresinstrument',
            name='tickunit',
            field=models.DecimalField(decimal_places=8, max_digits=14, verbose_name='호가 단위'),
        ),
    ]
