# Generated by Django 2.2 on 2019-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20191222_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresinstrument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
